name: Build and push to GHCR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    type: [ published ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:latest
